require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://postgres.nospmbecmxuzeobehhso:y!49Uv,FBNc6-qa@aws-0-eu-west-1.pooler.supabase.com:6543/postgres',
  ssl: { rejectUnauthorized: false },
});

const ingredients = [
  // SAFE - Water & Base
  ['water', 'LOW', 'A universal solvent and base ingredient found in most cosmetics. Safe for all skin types.'],
  ['aqua', 'LOW', 'Latin for water. Safe universal solvent and base for cosmetics.'],
  ['deionized water', 'LOW', 'Purified water free of minerals. Safe base ingredient.'],
  ['distilled water', 'LOW', 'Purified water. Safe base ingredient for cosmetics.'],

  // SAFE - Humectants & Moisturizers
  ['glycerin', 'LOW', 'A humectant that attracts moisture to skin. Safe and widely used in skincare.'],
  ['glycerol', 'LOW', 'Another name for glycerin. A safe, effective humectant.'],
  ['hyaluronic acid', 'LOW', 'A powerful humectant that holds 1000x its weight in water. Safe for all skin types.'],
  ['sodium hyaluronate', 'LOW', 'Salt form of hyaluronic acid. Safe and effective moisturizer.'],
  ['propylene glycol', 'LOW', 'A humectant and solvent. Generally safe at cosmetic concentrations.'],
  ['butylene glycol', 'LOW', 'A humectant and solvent. Safe at normal cosmetic use levels.'],
  ['pentylene glycol', 'LOW', 'A moisturizing agent with mild antimicrobial properties. Safe.'],
  ['sorbitol', 'LOW', 'A sugar alcohol humectant. Safe for cosmetic use.'],
  ['betaine', 'LOW', 'A natural humectant from sugar beets. Safe and soothing.'],
  ['urea', 'LOW', 'A natural moisturizing factor. Safe and effective for dry skin.'],
  ['panthenol', 'LOW', 'Provitamin B5. Safe and soothing moisturizer.'],
  ['allantoin', 'LOW', 'A skin conditioner and soother. Safe for sensitive skin.'],
  ['sodium pca', 'LOW', 'Natural moisturizing factor found in skin. Safe humectant.'],

  // SAFE - Emollients & Oils
  ['dimethicone', 'LOW', 'A silicone that smooths and protects skin. Safe for most skin types.'],
  ['cyclomethicone', 'LOW', 'A lightweight silicone. Safe for cosmetic use.'],
  ['cyclopentasiloxane', 'LOW', 'A volatile silicone. Safe at cosmetic concentrations.'],
  ['cyclohexasiloxane', 'LOW', 'A silicone emollient. Safe for cosmetic use.'],
  ['phenyl trimethicone', 'LOW', 'A silicone that adds shine. Safe cosmetic ingredient.'],
  ['jojoba oil', 'LOW', 'A natural plant wax that mimics skin sebum. Safe for all skin types.'],
  ['simmondsia chinensis seed oil', 'LOW', 'Jojoba oil. Safe natural emollient.'],
  ['argan oil', 'LOW', 'Rich in vitamin E and fatty acids. Safe and beneficial for skin and hair.'],
  ['argania spinosa kernel oil', 'LOW', 'Argan oil. Safe natural emollient rich in vitamin E.'],
  ['coconut oil', 'LOW', 'Natural emollient. Safe but may clog pores for acne-prone skin.'],
  ['cocos nucifera oil', 'LOW', 'Coconut oil. Natural emollient, may clog pores for some.'],
  ['rosehip oil', 'LOW', 'Rich in vitamins and fatty acids. Safe and beneficial for skin.'],
  ['rosa canina fruit oil', 'LOW', 'Rosehip oil. Safe natural oil rich in fatty acids.'],
  ['olive oil', 'LOW', 'Natural emollient rich in fatty acids. Safe for most skin types.'],
  ['olea europaea fruit oil', 'LOW', 'Olive oil. Safe natural emollient.'],
  ['sweet almond oil', 'LOW', 'Lightweight natural oil. Safe emollient for skin and hair.'],
  ['prunus amygdalus dulcis oil', 'LOW', 'Sweet almond oil. Safe natural emollient.'],
  ['sunflower seed oil', 'LOW', 'Lightweight natural oil rich in vitamin E. Safe for all skin types.'],
  ['helianthus annuus seed oil', 'LOW', 'Sunflower oil. Safe natural emollient.'],
  ['shea butter', 'LOW', 'Rich natural butter with fatty acids and vitamins. Safe and moisturizing.'],
  ['butyrospermum parkii butter', 'LOW', 'Shea butter. Safe and effective natural moisturizer.'],
  ['cocoa butter', 'LOW', 'Natural emollient from cocoa beans. Safe and moisturizing.'],
  ['theobroma cacao seed butter', 'LOW', 'Cocoa butter. Safe natural emollient.'],
  ['mineral oil', 'LOW', 'A lightweight emollient that seals in moisture. Safe and non-comedogenic at cosmetic grade.'],
  ['paraffinum liquidum', 'LOW', 'Mineral oil. Safe emollient and moisturizer.'],
  ['petrolatum', 'LOW', 'Petroleum jelly. Highly effective barrier. Safe at cosmetic grade.'],
  ['squalane', 'LOW', 'A stable emollient that mimics skin sebum. Safe for all skin types.'],
  ['squalene', 'LOW', 'Natural emollient found in skin. Safe at cosmetic concentrations.'],
  ['ceramide np', 'LOW', 'A ceramide that strengthens the skin barrier. Safe and beneficial.'],
  ['ceramide ap', 'LOW', 'A ceramide for skin barrier support. Safe and beneficial.'],
  ['ceramide eop', 'LOW', 'A ceramide for skin barrier repair. Safe and beneficial.'],
  ['ceramide 1', 'LOW', 'Skin barrier lipid. Safe and beneficial.'],
  ['ceramide 2', 'LOW', 'Skin barrier lipid. Safe and beneficial.'],
  ['ceramide 3', 'LOW', 'Skin barrier lipid. Safe and beneficial.'],
  ['cholesterol', 'LOW', 'A natural lipid that supports the skin barrier. Safe ingredient.'],
  ['fatty alcohol', 'LOW', 'Emollient alcohols that condition skin. Safe.'],
  ['cetyl alcohol', 'LOW', 'A fatty alcohol that softens skin. Safe emollient.'],
  ['stearyl alcohol', 'LOW', 'A fatty alcohol used as emollient. Safe cosmetic ingredient.'],
  ['cetearyl alcohol', 'LOW', 'A mixture of cetyl and stearyl alcohol. Safe emollient.'],
  ['behenyl alcohol', 'LOW', 'A fatty alcohol emollient. Safe for cosmetic use.'],
  ['caprylic/capric triglyceride', 'LOW', 'Lightweight emollient from coconut oil. Safe for all skin types.'],
  ['c12-15 alkyl benzoate', 'LOW', 'A lightweight emollient. Safe at cosmetic concentrations.'],
  ['isopropyl myristate', 'LOW', 'An emollient. Safe at cosmetic concentrations, may clog pores.'],
  ['isopropyl palmitate', 'LOW', 'An emollient. Safe but may be comedogenic for some.'],
  ['octyldodecanol', 'LOW', 'A fatty alcohol emollient. Safe cosmetic ingredient.'],
  ['neopentyl glycol diheptanoate', 'LOW', 'An emollient. Safe at cosmetic use levels.'],

  // SAFE - Active Ingredients
  ['niacinamide', 'LOW', 'Vitamin B3. Safe and effective for brightening, pore minimizing, and anti-aging.'],
  ['vitamin c', 'LOW', 'Ascorbic acid. Safe antioxidant that brightens and protects skin.'],
  ['ascorbic acid', 'LOW', 'Vitamin C. Safe antioxidant and brightening agent.'],
  ['ascorbyl glucoside', 'LOW', 'Stable vitamin C derivative. Safe brightening ingredient.'],
  ['sodium ascorbyl phosphate', 'LOW', 'Stable vitamin C derivative. Safe antioxidant.'],
  ['ascorbyl tetraisopalmitate', 'LOW', 'Oil-soluble vitamin C. Safe antioxidant.'],
  ['3-o-ethyl ascorbic acid', 'LOW', 'Stable vitamin C derivative. Safe brightening ingredient.'],
  ['tocopherol', 'LOW', 'Vitamin E. A safe antioxidant that protects and moisturizes skin.'],
  ['tocopheryl acetate', 'LOW', 'Vitamin E acetate. Safe antioxidant and skin conditioner.'],
  ['retinol', 'LOW', 'Vitamin A derivative. Safe for anti-aging at cosmetic concentrations.'],
  ['retinyl palmitate', 'LOW', 'Mild vitamin A derivative. Safe at cosmetic concentrations.'],
  ['retinyl acetate', 'LOW', 'Vitamin A derivative. Safe at normal cosmetic use levels.'],
  ['bakuchiol', 'LOW', 'Natural retinol alternative from seeds. Safe for all skin types.'],
  ['adenosine', 'LOW', 'A natural compound that helps with anti-aging. Safe for all skin types.'],
  ['centella asiatica extract', 'LOW', 'Soothing plant extract. Safe and beneficial for sensitive skin.'],
  ['madecassoside', 'LOW', 'Active compound from centella. Safe and soothing.'],
  ['asiaticoside', 'LOW', 'Active compound from centella. Safe and wound-healing.'],
  ['asiatic acid', 'LOW', 'Active compound from centella. Safe anti-inflammatory.'],
  ['madecassic acid', 'LOW', 'Active compound from centella. Safe and soothing.'],
  ['green tea extract', 'LOW', 'Rich in antioxidants. Safe and beneficial for skin.'],
  ['camellia sinensis leaf extract', 'LOW', 'Green tea extract. Safe antioxidant-rich ingredient.'],
  ['epigallocatechin gallate', 'LOW', 'Green tea antioxidant. Safe and protective.'],
  ['licorice root extract', 'LOW', 'Safe brightening ingredient that inhibits melanin production.'],
  ['glycyrrhiza glabra root extract', 'LOW', 'Licorice extract. Safe brightening and anti-inflammatory.'],
  ['kojic acid', 'LOW', 'Brightening ingredient from fermentation. Safe at cosmetic concentrations.'],
  ['alpha arbutin', 'LOW', 'A safe and effective brightening ingredient.'],
  ['arbutin', 'LOW', 'Skin brightening ingredient. Safe at normal cosmetic concentrations.'],
  ['azelaic acid', 'LOW', 'Multi-benefit acid for acne and brightening. Safe for most skin types.'],
  ['tranexamic acid', 'LOW', 'Brightening ingredient. Safe at cosmetic concentrations.'],
  ['lactic acid', 'LOW', 'An AHA exfoliant from milk. Safe at cosmetic concentrations with proper pH.'],
  ['glycolic acid', 'LOW', 'An AHA exfoliant. Effective but use with sun protection. Safe at cosmetic concentrations.'],
  ['mandelic acid', 'LOW', 'A gentle AHA. Safe for most skin types including sensitive.'],
  ['malic acid', 'LOW', 'A gentle AHA. Safe at cosmetic concentrations.'],
  ['citric acid', 'LOW', 'Used to adjust pH and as a mild exfoliant. Safe at cosmetic use levels.'],
  ['salicylic acid', 'LOW', 'A BHA exfoliant. Safe and effective for acne-prone skin at cosmetic concentrations.'],
  ['polyhydroxy acid', 'LOW', 'Gentle exfoliants safe for sensitive skin.'],
  ['gluconolactone', 'LOW', 'A gentle PHA exfoliant. Safe for sensitive skin.'],
  ['lactobionic acid', 'LOW', 'A gentle PHA. Safe for all skin types.'],
  ['resveratrol', 'LOW', 'An antioxidant from grapes. Safe and protective.'],
  ['ferulic acid', 'LOW', 'An antioxidant that boosts vitamin C. Safe for cosmetic use.'],
  ['coenzyme q10', 'LOW', 'An antioxidant. Safe and beneficial for skin.'],
  ['ubiquinone', 'LOW', 'Coenzyme Q10. Safe antioxidant.'],
  ['idebenone', 'LOW', 'A powerful antioxidant. Safe at cosmetic concentrations.'],
  ['astaxanthin', 'LOW', 'A potent antioxidant. Safe at cosmetic concentrations.'],

  // SAFE - Sunscreen Actives
  ['zinc oxide', 'LOW', 'A physical/mineral sunscreen. Safe and effective for all skin types.'],
  ['titanium dioxide', 'LOW', 'A physical/mineral sunscreen. Safe and recommended for sensitive skin.'],
  ['octinoxate', 'LOW', 'A chemical UVB filter. Safe at approved concentrations in most regions.'],
  ['octisalate', 'LOW', 'A chemical UVB filter. Safe at approved concentrations.'],
  ['octocrylene', 'LOW', 'A chemical UV filter. Safe at approved cosmetic concentrations.'],
  ['avobenzone', 'LOW', 'A chemical UVA filter. Safe at approved concentrations.'],
  ['homosalate', 'LOW', 'A chemical UVB filter. Generally safe at approved concentrations.'],
  ['tinosorb s', 'LOW', 'A broad-spectrum UV filter. Safe and effective.'],
  ['tinosorb m', 'LOW', 'A broad-spectrum UV filter. Safe and effective.'],
  ['uvinul a plus', 'LOW', 'A UVA filter. Safe at approved concentrations.'],
  ['uvinul t 150', 'LOW', 'A UVB filter. Safe at approved concentrations.'],

  // SAFE - Emulsifiers & Stabilizers
  ['glyceryl stearate', 'LOW', 'An emulsifier and emollient. Safe for cosmetic use.'],
  ['peg-100 stearate', 'LOW', 'An emulsifier. Safe at normal cosmetic concentrations.'],
  ['polysorbate 20', 'LOW', 'An emulsifier and solubilizer. Safe at cosmetic use levels.'],
  ['polysorbate 60', 'LOW', 'An emulsifier. Safe at cosmetic concentrations.'],
  ['polysorbate 80', 'LOW', 'An emulsifier. Safe at cosmetic concentrations.'],
  ['sorbitan oleate', 'LOW', 'An emulsifier. Safe for cosmetic use.'],
  ['lecithin', 'LOW', 'A natural emulsifier from soy or eggs. Safe and skin-conditioning.'],
  ['sunflower lecithin', 'LOW', 'A natural emulsifier. Safe plant-based alternative.'],
  ['hydrogenated lecithin', 'LOW', 'A stable emulsifier. Safe for cosmetic use.'],
  ['sodium stearoyl lactylate', 'LOW', 'An emulsifier. Safe at cosmetic concentrations.'],
  ['ceteareth-20', 'LOW', 'An emulsifier. Safe at normal cosmetic use levels.'],
  ['steareth-2', 'LOW', 'An emulsifier. Safe at cosmetic concentrations.'],
  ['peg-40 hydrogenated castor oil', 'LOW', 'A solubilizer. Safe at cosmetic use levels.'],
  ['carbomer', 'LOW', 'A thickener and stabilizer. Safe and widely used in gels.'],
  ['acrylates/c10-30 alkyl acrylate crosspolymer', 'LOW', 'A thickener. Safe at cosmetic concentrations.'],
  ['xanthan gum', 'LOW', 'A natural thickener. Safe for all skin types.'],
  ['hydroxyethyl cellulose', 'LOW', 'A natural-derived thickener. Safe cosmetic ingredient.'],
  ['hydroxypropyl methylcellulose', 'LOW', 'A thickener. Safe for cosmetic use.'],
  ['carrageenan', 'LOW', 'A natural thickener from seaweed. Safe at cosmetic concentrations.'],
  ['guar gum', 'LOW', 'A natural thickener. Safe for cosmetic use.'],

  // SAFE - Preservatives
  ['phenoxyethanol', 'LOW', 'A widely used preservative. Safe at approved concentrations (≤1%).'],
  ['ethylhexylglycerin', 'LOW', 'A preservative booster and skin conditioner. Safe at cosmetic use levels.'],
  ['caprylyl glycol', 'LOW', 'A preservative and skin conditioning agent. Safe at cosmetic concentrations.'],
  ['sodium benzoate', 'LOW', 'A preservative. Safe at cosmetic concentrations.'],
  ['potassium sorbate', 'LOW', 'A natural preservative. Safe at cosmetic concentrations.'],
  ['benzoic acid', 'LOW', 'A preservative. Safe at approved cosmetic concentrations.'],
  ['sorbic acid', 'LOW', 'A natural preservative. Safe at cosmetic concentrations.'],
  ['dehydroacetic acid', 'LOW', 'A preservative. Safe at approved cosmetic concentrations.'],
  ['benzyl alcohol', 'LOW', 'A preservative and solvent. Safe at cosmetic concentrations, potential sensitizer at high levels.'],
  ['chlorphenesin', 'LOW', 'A preservative. Safe at cosmetic concentrations.'],
  ['1,2-hexanediol', 'LOW', 'A preservative and humectant. Safe at cosmetic concentrations.'],
  ['p-anisic acid', 'LOW', 'A natural preservative from anise. Safe at cosmetic use levels.'],

  // SAFE - pH Adjusters
  ['sodium hydroxide', 'LOW', 'Used to adjust pH. Safe at trace concentrations in finished products.'],
  ['potassium hydroxide', 'LOW', 'pH adjuster. Safe at trace amounts in finished cosmetics.'],
  ['triethanolamine', 'LOW', 'pH adjuster and emulsifier. Safe at cosmetic concentrations.'],
  ['arginine', 'LOW', 'An amino acid used as pH adjuster. Safe and skin-conditioning.'],
  ['lactic acid', 'LOW', 'Used to adjust pH. Safe at cosmetic concentrations.'],

  // SAFE - Proteins & Peptides
  ['hydrolyzed collagen', 'LOW', 'A protein that conditions skin and hair. Safe and beneficial.'],
  ['collagen', 'LOW', 'Skin protein. Safe as a cosmetic ingredient.'],
  ['hydrolyzed keratin', 'LOW', 'A protein for hair strengthening. Safe cosmetic ingredient.'],
  ['keratin', 'LOW', 'Hair protein. Safe cosmetic ingredient.'],
  ['hydrolyzed silk', 'LOW', 'A conditioning protein. Safe for skin and hair.'],
  ['silk amino acids', 'LOW', 'Conditioning proteins from silk. Safe cosmetic ingredient.'],
  ['hydrolyzed wheat protein', 'LOW', 'A conditioning protein. Safe but avoid if wheat-allergic.'],
  ['hydrolyzed soy protein', 'LOW', 'A conditioning protein. Safe but avoid if soy-allergic.'],
  ['palmitoyl pentapeptide-4', 'LOW', 'An anti-aging peptide. Safe and effective.'],
  ['palmitoyl tripeptide-1', 'LOW', 'An anti-aging peptide. Safe and effective.'],
  ['palmitoyl tetrapeptide-7', 'LOW', 'An anti-aging peptide. Safe at cosmetic concentrations.'],
  ['acetyl hexapeptide-3', 'LOW', 'An anti-wrinkle peptide. Safe at cosmetic concentrations.'],
  ['acetyl hexapeptide-8', 'LOW', 'An anti-wrinkle peptide. Safe at cosmetic concentrations.'],
  ['copper tripeptide-1', 'LOW', 'A peptide that promotes skin repair. Safe and beneficial.'],
  ['matrixyl', 'LOW', 'An anti-aging peptide. Safe at cosmetic concentrations.'],

  // SAFE - Botanical Extracts
  ['aloe vera', 'LOW', 'Soothing and moisturizing plant extract. Safe for all skin types.'],
  ['aloe barbadensis leaf juice', 'LOW', 'Aloe vera juice. Safe and soothing for all skin types.'],
  ['chamomile extract', 'LOW', 'Soothing anti-inflammatory extract. Safe for sensitive skin.'],
  ['matricaria flower extract', 'LOW', 'Chamomile extract. Safe and soothing.'],
  ['calendula extract', 'LOW', 'Soothing plant extract. Safe for sensitive and irritated skin.'],
  ['calendula officinalis flower extract', 'LOW', 'Calendula extract. Safe anti-inflammatory.'],
  ['lavender extract', 'LOW', 'Soothing plant extract. Safe at cosmetic concentrations.'],
  ['lavandula angustifolia flower extract', 'LOW', 'Lavender extract. Generally safe at cosmetic concentrations.'],
  ['rose extract', 'LOW', 'Soothing and hydrating plant extract. Safe for most skin types.'],
  ['rosa damascena flower extract', 'LOW', 'Rose extract. Safe and soothing.'],
  ['cucumber extract', 'LOW', 'Soothing and hydrating extract. Safe for all skin types.'],
  ['cucumis sativus fruit extract', 'LOW', 'Cucumber extract. Safe and soothing.'],
  ['green tea extract', 'LOW', 'Rich in antioxidants. Safe and beneficial.'],
  ['witch hazel extract', 'LOW', 'Astringent plant extract. Safe at cosmetic concentrations.'],
  ['hamamelis virginiana extract', 'LOW', 'Witch hazel. Safe astringent.'],
  ['oat extract', 'LOW', 'Soothing and moisturizing. Safe for sensitive skin.'],
  ['avena sativa kernel extract', 'LOW', 'Oat extract. Safe and soothing for sensitive skin.'],
  ['sea kelp extract', 'LOW', 'Rich in minerals. Safe and beneficial.'],
  ['niacinamide', 'LOW', 'Vitamin B3. Safe and multifunctional skin ingredient.'],
  ['panthenol', 'LOW', 'Provitamin B5. Safe and soothing.'],
  ['bisabolol', 'LOW', 'A soothing compound from chamomile. Safe for sensitive skin.'],
  ['alpha-bisabolol', 'LOW', 'Soothing compound. Safe for all skin types.'],
  ['dipotassium glycyrrhizate', 'LOW', 'Licorice-derived anti-inflammatory. Safe and soothing.'],
  ['zinc gluconate', 'LOW', 'A zinc compound that helps with acne. Safe at cosmetic concentrations.'],
  ['turmeric extract', 'LOW', 'Anti-inflammatory extract. Safe at cosmetic concentrations.'],
  ['curcuma longa root extract', 'LOW', 'Turmeric extract. Safe anti-inflammatory.'],

  // RISKY - Fragrances & Allergens
  ['fragrance', 'MEDIUM', 'A common skin sensitizer and allergen. May cause irritation in sensitive individuals.'],
  ['parfum', 'MEDIUM', 'Fragrance blend. May contain allergens and cause skin sensitization.'],
  ['linalool', 'MEDIUM', 'A fragrance component. Can cause allergic reactions in sensitive individuals.'],
  ['limonene', 'MEDIUM', 'A fragrance component. Known skin sensitizer when oxidized.'],
  ['geraniol', 'MEDIUM', 'A fragrance alcohol. Can cause skin sensitization.'],
  ['citronellol', 'MEDIUM', 'A fragrance component. Potential skin sensitizer.'],
  ['eugenol', 'MEDIUM', 'A fragrance component. Can cause allergic contact dermatitis.'],
  ['cinnamal', 'MEDIUM', 'A fragrance component. Known allergen.'],
  ['isoeugenol', 'MEDIUM', 'A fragrance component. Known skin allergen.'],
  ['citral', 'MEDIUM', 'A fragrance component. Can cause sensitization.'],
  ['coumarin', 'MEDIUM', 'A fragrance component. Potential allergen.'],
  ['benzyl salicylate', 'MEDIUM', 'A fragrance component. Potential skin allergen.'],
  ['hexyl cinnamal', 'MEDIUM', 'A fragrance chemical. Potential sensitizer.'],
  ['amyl cinnamal', 'MEDIUM', 'A fragrance component. Known allergen in the EU.'],
  ['hydroxycitronellal', 'MEDIUM', 'A fragrance component. Known allergen.'],
  ['farnesol', 'MEDIUM', 'A fragrance component. Potential skin sensitizer.'],
  ['benzyl benzoate', 'MEDIUM', 'A fragrance and solvent. Potential allergen.'],
  ['benzyl cinnamate', 'MEDIUM', 'A fragrance component. Potential allergen.'],
  ['alpha-isomethyl ionone', 'MEDIUM', 'A fragrance component. Potential allergen.'],
  ['methyl 2-octynoate', 'MEDIUM', 'A fragrance component. Potential allergen.'],

  // RISKY - Alcohols
  ['alcohol denat', 'MEDIUM', 'Denatured alcohol. Can dry out skin and disrupt barrier with regular use.'],
  ['ethanol', 'MEDIUM', 'Alcohol. Can be drying and irritating for dry or sensitive skin.'],
  ['isopropyl alcohol', 'MEDIUM', 'Rubbing alcohol. Drying and potentially irritating for skin.'],
  ['sd alcohol', 'MEDIUM', 'Denatured alcohol. Can be drying with prolonged use.'],
  ['sd alcohol 40', 'MEDIUM', 'Denatured alcohol. May dry out skin with regular use.'],

  // RISKY - Potentially Comedogenic
  ['lanolin', 'MEDIUM', 'Animal-derived emollient. Effective but may cause sensitivity in some. Can clog pores.'],
  ['lanolin alcohol', 'MEDIUM', 'Emollient from wool wax. Potential sensitizer for some individuals.'],
  ['acetylated lanolin', 'MEDIUM', 'Modified lanolin. Potential sensitizer, may be comedogenic.'],
  ['wheat germ oil', 'MEDIUM', 'High in fatty acids but highly comedogenic. Avoid if acne-prone.'],
  ['linseed oil', 'MEDIUM', 'Omega-rich oil. May be comedogenic for acne-prone skin.'],

  // RISKY - Chemical Filters
  ['oxybenzone', 'MEDIUM', 'A chemical sunscreen filter. Potential endocrine disruptor concerns, skin allergen for some.'],
  ['benzophenone-3', 'MEDIUM', 'Oxybenzone. Potential hormonal disruption concerns at high absorption levels.'],
  ['cinoxate', 'MEDIUM', 'A UV filter. Potential allergen, avoid if sun-sensitive.'],

  // RISKY - Other Concerns
  ['formaldehyde releasers', 'MEDIUM', 'Preservatives that release formaldehyde. Potential sensitizer.'],
  ['dmdm hydantoin', 'MEDIUM', 'A formaldehyde-releasing preservative. Potential sensitizer and allergen.'],
  ['imidazolidinyl urea', 'MEDIUM', 'A formaldehyde-releasing preservative. Potential allergen.'],
  ['diazolidinyl urea', 'MEDIUM', 'A formaldehyde-releasing preservative. Potential sensitizer.'],
  ['quaternium-15', 'MEDIUM', 'A formaldehyde-releasing preservative. Frequent allergen.'],
  ['bronopol', 'MEDIUM', 'A preservative that can release formaldehyde. Potential sensitizer.'],
  ['2-bromo-2-nitropropane-1,3-diol', 'MEDIUM', 'Bronopol. Can release formaldehyde. Potential allergen.'],
  ['methylisothiazolinone', 'MEDIUM', 'A preservative. Known skin sensitizer, banned from leave-on products in EU.'],
  ['methylchloroisothiazolinone', 'MEDIUM', 'A preservative. Strong sensitizer, restricted in EU leave-on products.'],
  ['mi/mci', 'MEDIUM', 'Methylisothiazolinone/Methylchloroisothiazolinone. Strong sensitizers.'],
  ['kathon cg', 'MEDIUM', 'MI/MCI blend. Strong skin sensitizer.'],
  ['iodopropynyl butylcarbamate', 'MEDIUM', 'A preservative. Potential sensitizer, restricted in some regions.'],
  ['sodium lauryl sulfate', 'MEDIUM', 'A surfactant. Can be drying and irritating, especially for sensitive skin.'],
  ['sls', 'MEDIUM', 'Sodium lauryl sulfate. Known skin irritant at high concentrations.'],
  ['ammonium lauryl sulfate', 'MEDIUM', 'A surfactant. Potential skin irritant similar to SLS.'],
  ['sodium laureth sulfate', 'MEDIUM', 'A milder surfactant than SLS but can still cause irritation.'],
  ['sles', 'MEDIUM', 'Sodium laureth sulfate. Milder than SLS but still potentially irritating.'],
  ['toluene', 'MEDIUM', 'A solvent used in nail products. Volatile and potentially toxic with prolonged exposure.'],
  ['ethyl tosylamide', 'MEDIUM', 'Used in nail products. Restricted in some regions.'],
  ['triphenyl phosphate', 'MEDIUM', 'Plasticizer used in nail products. Potential endocrine disruptor.'],
  ['phthalates', 'MEDIUM', 'Plasticizers. Potential endocrine disruptors.'],
  ['dibutyl phthalate', 'MEDIUM', 'A plasticizer. Restricted in EU cosmetics.'],
  ['p-phenylenediamine', 'MEDIUM', 'Hair dye ingredient. Strong allergen.'],
  ['ppd', 'MEDIUM', 'Para-phenylenediamine in hair dye. Frequent contact allergen.'],
  ['propylparaben', 'MEDIUM', 'A preservative. Some concerns about endocrine disruption at high levels.'],
  ['butylparaben', 'MEDIUM', 'A preservative. Potential endocrine disruption concerns.'],
  ['isobutylparaben', 'MEDIUM', 'A preservative. Potential endocrine disruption concerns.'],
  ['isopropylparaben', 'MEDIUM', 'A preservative. Potential endocrine disruption concerns.'],
  ['methylparaben', 'MEDIUM', 'A widely used preservative. Generally safe but some endocrine concerns.'],
  ['ethylparaben', 'MEDIUM', 'A preservative. Generally safe but some endocrine disruption concerns.'],
  ['triethanolamine', 'MEDIUM', 'pH adjuster. Can form nitrosamines with certain ingredients. Generally safe.'],
  ['bha', 'MEDIUM', 'Butylated hydroxyanisole. An antioxidant preservative. Potential endocrine disruptor concerns.'],
  ['butylated hydroxyanisole', 'MEDIUM', 'An antioxidant. Potential endocrine disruption concerns at high levels.'],
  ['resorcinol', 'MEDIUM', 'Used in hair dyes and some treatments. Restricted in EU leave-on products.'],
  ['ethanolamines', 'MEDIUM', 'pH adjusters. Can form carcinogenic nitrosamines with certain ingredients.'],
  ['diethanolamine', 'MEDIUM', 'pH adjuster/emulsifier. Potential nitrosamine formation concerns.'],
  ['coal tar', 'MEDIUM', 'Used in anti-dandruff and psoriasis products. Potential carcinogen concerns.'],

  // HIGH RISK - Restricted/Banned
  ['mercury', 'HIGH', 'A toxic heavy metal. Banned in cosmetics in most countries. Extremely dangerous.'],
  ['mercuric chloride', 'HIGH', 'Mercury compound. Banned in cosmetics. Highly toxic.'],
  ['ammoniated mercury', 'HIGH', 'Mercury compound. Banned in cosmetics. Toxic.'],
  ['formaldehyde', 'HIGH', 'A preservative. Carcinogen at high levels. Restricted in cosmetics.'],
  ['hydroquinone', 'HIGH', 'A skin bleaching agent. Restricted or banned in many countries due to safety concerns.'],
  ['arsenic', 'HIGH', 'A toxic heavy metal. Banned in cosmetics. Carcinogen.'],
  ['lead', 'HIGH', 'A toxic heavy metal. Restricted in cosmetics. Neurotoxin.'],
  ['lead acetate', 'HIGH', 'Lead compound. Banned in cosmetics in EU. Toxic.'],
  ['chromium vi', 'HIGH', 'Hexavalent chromium. Carcinogen. Banned in cosmetics.'],
  ['cadmium', 'HIGH', 'A toxic heavy metal. Banned in cosmetics.'],
  ['bithionol', 'HIGH', 'A preservative. Banned in cosmetics in many countries.'],
  ['chloroform', 'HIGH', 'A solvent. Banned in cosmetics due to toxicity.'],
  ['vinyl chloride', 'HIGH', 'A propellant. Carcinogen. Banned in cosmetics.'],
  ['zirconium', 'HIGH', 'Certain zirconium compounds banned in aerosol cosmetics.'],
  ['halogenated salicylanilides', 'HIGH', 'Antimicrobials. Banned in cosmetics.'],
  ['hexachlorophene', 'HIGH', 'An antibacterial. Banned in cosmetics due to neurotoxicity.'],
  ['dihydrostreptomycin', 'HIGH', 'An antibiotic. Not for use in cosmetics.'],
  ['neomycin', 'HIGH', 'An antibiotic. Not approved for cosmetic use.'],
  ['placental extracts', 'HIGH', 'Human placenta-derived ingredients. Restricted in many countries.'],
  ['tretinoin', 'HIGH', 'Prescription retinoid. Not allowed in over-the-counter cosmetics.'],
  ['isotretinoin', 'HIGH', 'Prescription retinoid. Banned in cosmetics.'],
  ['steroids', 'HIGH', 'Corticosteroids. Not permitted in cosmetics without prescription.'],
  ['hydrocortisone', 'HIGH', 'A steroid. Restricted to prescription in most countries.'],
  ['minoxidil', 'HIGH', 'A hair growth drug. Prescription-only in most countries.'],
  ['clobetasol', 'HIGH', 'A potent corticosteroid. Prescription-only. Not for cosmetic use.'],
  ['triclosan', 'HIGH', 'An antimicrobial. Banned from rinse-off products in the US. Restricted in EU.'],
  ['triclocarban', 'HIGH', 'An antimicrobial. Restricted/banned in many countries.'],
  ['nitrosamines', 'HIGH', 'Carcinogenic compounds. Must be below trace levels in cosmetics.'],
  ['benzene', 'HIGH', 'A carcinogenic solvent. Not permitted in cosmetics.'],
  ['1,4-dioxane', 'HIGH', 'A carcinogenic contaminant. Should be absent from cosmetics.'],
  ['ethylene oxide', 'HIGH', 'A carcinogenic gas. Not permitted in cosmetics.'],
  ['polycyclic musks', 'HIGH', 'Certain synthetic musks. Restricted due to bioaccumulation concerns.'],
  ['galaxolide', 'HIGH', 'A synthetic musk. Restricted due to endocrine disruption concerns.'],
  ['tonalide', 'HIGH', 'A synthetic musk. Restricted due to endocrine disruption concerns.'],
];

async function seed() {
  console.log(`Seeding ${ingredients.length} ingredients...`);

  let inserted = 0;
  let skipped = 0;

  for (const [name, risk, reason] of ingredients) {
    try {
      const result = await pool.query(
        `INSERT INTO dataset_rows (ingredient_name, risk_level, reason)
         VALUES ($1, $2, $3)
         ON CONFLICT (ingredient_name) DO NOTHING`,
        [name.toLowerCase().trim(), risk, reason]
      );
      if (result.rowCount > 0) inserted++;
      else skipped++;
    } catch (e) {
      console.error(`Failed to insert "${name}":`, e.message);
    }
  }

  console.log(`Done. Inserted: ${inserted}, Skipped (already existed): ${skipped}`);
  const count = await pool.query('SELECT COUNT(*) FROM dataset_rows');
  console.log(`Total dataset_rows: ${count.rows[0].count}`);
  pool.end();
}

seed().catch(e => { console.error(e); pool.end(); });
